server:
  port: 8000

spring:
  application: telegram-broadcast

telegram:
  bot:
    token: 'YOUR-BOT-TOKEN'
    username: 'YOUR-BOT-USERNAME'
  chat-id: 'YOUR-CHAT-ID'
  base-url: https://api.telegram.org/bot